if(!Array.prototype.map)Array.prototype.map=function(a,f){for(var j=this.length,d=new Array(j),h=0;h<j;h++)if(h in this)d[h]=a.call(f,this[h],h,this);return d};if(!Array.prototype.filter)Array.prototype.filter=function(a,f){for(var j=this.length,d=[],h=0;h<j;h++)if(h in this){var b=this[h];a.call(f,b,h,this)&&d.push(b)}return d};if(!Array.prototype.forEach)Array.prototype.forEach=function(a,f){for(var j=this.length>>>0,d=0;d<j;d++)d in this&&a.call(f,this[d],d,this)};
if(!Array.prototype.reduce)Array.prototype.reduce=function(a,f){var j=this.length;if(!j&&arguments.length==1)throw new Error("reduce: empty array, no initial value");var d=0;if(arguments.length<2)for(;;){if(d in this){f=this[d++];break}if(++d>=j)throw new Error("reduce: no values, no initial value");}for(;d<j;d++)if(d in this)f=a(f,this[d],d,this);return f};var dv={};dv.version={major:0,minor:1};dv.error=function(a){typeof console=="undefined"?alert(a):console.error(a)};
dv.listen=function(a,f,j){j=dv.listener(j);return a.addEventListener?a.addEventListener(f,j,false):a.attachEvent("on"+f,j)};dv.listener=function(a){return a.$listener||(a.$listener=function(f){try{dv.event=f;return a.call(this,f)}finally{delete dv.event}})};dv.array=function(a){for(var f=[],j=0;j<a;++j)f.push(0);return f};dv.keys=function(a){var f=[];for(var j in a)f.push(j);return f};
dv.range=function(a,f,j){if(arguments.length==1){f=a;a=0}if(j==null)j=1;if((f-a)/j==Infinity)throw new Error("infinite range");var d=[],h=-1,b;if(j<0)for(;(b=a+j*++h)>f;)d.push(b);else for(;(b=a+j*++h)<f;)d.push(b);return d};dv.time=function(a){var f=Date.now();a();return Date.now()-f};dv.compare_time=function(a,f){return dv.time(a)/dv.time(f)};dv.rand={};dv.rand.uniform=function(a,f){a=a||0;f=f||1;var j=f-a;return function(){return a+j*Math.random()}};
dv.rand.integer=function(a,f){if(f===undefined){f=a;a=0}return function(){return a+Math.max(0,Math.floor(f*(Math.random()-0.0010)))}};dv.rand.normal=function(a,f){a=a||0;f=f||1;var j=undefined;return function(){var d=0,h=0,b;if(j!==undefined){d=j;j=undefined;return d}do{d=Math.random()*2-1;h=Math.random()*2-1;b=d*d+h*h}while(b==0||b>1);b=Math.sqrt(-2*Math.log(b)/b);j=a+h*b*f;return a+d*b*f}};
function typeOf(a){var f=typeof a;if(f==="object")if(a){if(typeof a.length==="number"&&!a.propertyIsEnumerable("length")&&typeof a.splice==="function")f="array"}else f="null";return f}dv.ivar=function(a,f){if(typeOf(f)!="array")f=[f];f.forEach(function(j){var d;if(typeOf(j)==="object"){d=j.initial;j=j.name}var h="_"+j;a[h]=d;a[j]=function(b){if(arguments.length){a[h]=b;return a}return a[h]}})};
dv.ivara=function(a,f){if(typeOf(f)!="array")f=[f];f.forEach(function(j){var d;if(typeOf(j)==="object"){d=j.initial;if(d!=undefined&&typeOf(d)!="array")d=[d];j=j.name}var h="_"+j;a[h]=d;a[j]=function(b){if(arguments.length){a[h]=typeOf(b)==="array"?b:[b];return a}return a[h]}})};
dv.dom=function(a){if(a instanceof jQuery)return a;if(typeof a==="string")a={type:"textNode",value:a};var f=a.type||"div",j;switch(f){case "textNode":j=jQuery(document.createTextNode(a.value));break;case "input":case "div":case "label":case "select":case "span":case "button":case "li":case "textArea":case "ul":case "p":case "a":j=jQuery(document.createElement(f));break;default:throw new Error("invalid element type in build tree of dom utility");}(a.classes||[]).forEach(function(b){j.addClass(b)});
(a.selectOptions||[]).forEach(function(b){var n=document.createElement("option");n.text=b.label;n.value=b.value;j.attr("options").add(n)});var d=a.extraAttrs||a.attrs||{};pv.keys(d).forEach(function(b){j.attr(b,d[b])});(a.children||[]).forEach(function(b){j.append(dv.dom(b))});var h=a.events||{};pv.keys(h).forEach(function(b){j[b].call(j,h[b])});return j};dv.log=function(a,f){return f?Math.log(a)/Math.log(f):Math.log(a)};dv.type={nominal:"nominal",ordinal:"ordinal",numeric:"numeric",unknown:"unknown"};
dv.table=function(a,f){function j(g){for(var i=[],k={},o,p=0;p<g.length;++p)if(k[o=g[p]]===undefined){k[o]=1;i.push(o)}return i.sort()}function d(g){if(l(g)!=undefined)g="_"+g;if(g===undefined)g="_";for(var i=g=g.replace(/ /g,"_");b[i]!=undefined;){if(i=m[g])m[g]++;else m[g]=1;i=g+m[g]}return i}function h(g){return g.reduce(function(i,k,o){i[k]=o;return i},{})}var b=[],n={};b.addColumn=function(g,i,k,o,p,r){r=r||{};k=k||dv.type.unknown;o=o;p=p;g=d(g);var s=i;if(r.compressAll||r.compress&&(k===dv.type.nominal||
k===dv.type.ordinal)){s=[];s.lut=j(i);for(var x=0,F=h(s.lut);x<i.length;++x)s.push(F[i[x]])}s.name=g;s.wrangler_type=o;s.wrangler_role=p;s.index=function(){for(var q=0;q<b.length;++q)if(b[q].name===this.name)return q;return-1};s.type=k;s.table=b;s.setName=function(q){var t=s.name;if(t!==q){q=d(q);s.name=q;delete b[t];b[q]=s}};r.index===undefined?b.push(s):b.splice(r.index,0,s);b[g]=s};b.metadata=function(g,i){if(arguments.length>1){n[g]=i;return b}else return n[g]};b.removeColumn=function(g){g=b[g]||
null;if(g!=null){delete b[g.name];b.splice(g.index(),1)}return g};b.slice=function(g,i,k){g=g||0;if(i===undefined)i=b.rows();var o=b.map(function(p){return{name:p.name,type:p.type,values:p.slice(g,i),wrangler_type:p.wrangler_type,wrangler_role:p.wrangler_role}});return dv.table(o,k)};b.slice_cols=function(g,i){g=g||0;i=i||b.cols();for(var k=b.slice(),o=i;o<b.cols();++o)k.removeColumn(i);for(o=0;o<g;++o)k.removeColumn(0);return k};b.rows=function(){return b[0]?b[0].length:0};b.row=function(g){return b.map(function(i){return i[g]})};
b.cols=function(){return b.length};b.names=function(){return b.map(function(g){return g.name})};b.types=function(){return b.map(function(g){return g.wrangler_type})};b.query=function(g){var i=[],k=[1],o=g.dims,p=g.narm,r=g.filter?g.filter.table(b):undefined,s=g.result,x=g.limit||1E4,F=g.warn||false;if(o){k=[];for(w=0;w<g.dims.length;++w){var q=g.dims[w],t=typeof q;if(t==="string"||t==="number")y=b[q];else if(q.array)y=q.array(b[q.value]);else if(q.values){y=q.values;y.lut=q.lut}i.push(y);k.push(y.lut.length)}}g=
g.vals;var C=k.reduce(function(G,V){return G*V},1),H=b[0].length,y,A,O,B,M,N,J,K,L,P,Q,R,S,T,U,D={};y={};var I=[],w=0,z=t=q=0;x&&C>x&&F&&alert("This unfold operation requires computing over 10,000 values.  We currently do not support operations this large and will preview only a subset of values created.");C=x?Math.min(x,C):C;q=false;for(w=0;w<g.length;++w){t=g[w].init();for(B in t)if(B=="*"){t[B].map(function(G){D[G]=dv.array(C)});q=true}else{z=b[B].index();O=b[B].name;t[B].map(function(G){D[G+"_"+
O]=D[G+"_"+z]=dv.array(C)});if(!y[z]){y[z]=true;I.push(z)}}}I.length==0&&q&&I.push(-1);w=0;for(x=[1];w<k.length;++w)x.push(x[w]*k[w]);for(q=0;q<I.length;++q){B=I[q];P=(F=D.cnt)&&q==0;M=D["sum_"+B];Q=M!==undefined;N=D["ssq_"+B];R=N!==undefined;J=D["min_"+B];S=J!==undefined;K=D["max_"+B];T=K!==undefined;L=D["first_"+B];U=L!==undefined;y=b[B];for(w=0;w<H;++w){if(y)A=y[w];for(t=z=0;t<k.length;++t)z+=x[t]*(o?i[t][w]:0);if(!(p&&isNaN(A)))if(!(r&&!r.test(w))){if(P)F[z]+=1;if(Q)M[z]+=A;if(R)N[z]+=A*A;if(U&&
!L[z])L[z]=y.lut[A];if(S&&A<J[z])J[z]=A;if(T&&A>K[z])K[z]=A}}}s=[];p=1;for(w=0;w<i.length;++w){y=[];o=i[w].lut;r=k[w];t=q=A=0;for(c=-1;q<C;++q,++t){if(t==p){t=0;A=(A+1)%r}y[q]=o[A]}p*=r;y.unique=o.length;s.push(y)}g.map(function(G){s.push(G.done(D))});return s};var m={},l=function(g){var i=Number(g);if(!(isNaN(i)||!i&&(g+"").indexOf("0")===-1||parseInt(i)!=i))return i};if(typeOf(a)==="string")a=[{name:"data",values:[a],type:dv.type.nominal}];a.forEach(function(g){b.addColumn(g.name,g.values,g.type,
g.wrangler_type,g.wrangler_role,f)});return b};dv.noop=function(){};dv.first=function(a){var f={};f.init=function(){var j={};j[a]=["first"];return j};f.done=function(j){return j["first_"+a]};f.value=a;return f};dv.count=function(a){var f={};f.init=function(){return{"*":["cnt"]}};f.done=function(j){return j.cnt};f.value=a;return f};dv.min=function(a){var f={};f.init=function(){var j={};j[a]=["min"];return j};f.done=function(j){return j["min_"+a]};f.value=a;return f};
dv.max=function(a){var f={};f.init=function(){var j={};j[a]=["max"];return j};f.done=function(j){return j["max_"+a]};f.value=a;return f};dv.sum=function(a){var f={};f.init=function(){var j={};j[a]=["sum"];return j};f.done=function(j){return j["sum_"+a]};f.value=a;return f};dv.avg=function(a){var f={};f.init=function(){var j={"*":["cnt"]};j[a]=["sum"];return j};f.done=function(j){var d="avg_"+a,h=j[d];if(!h){var b=j.cnt;j[d]=h=j["sum_"+a].map(function(n,m){return n/b[m]})}return h};f.value=a;return f};
dv.variance=function(a,f){var j={},d=f?1:0;j.init=function(){var h={"*":["cnt"]};h[a]=["sum","ssq"];return h};j.done=function(h){var b=h.cnt,n=h["sum_"+a],m=h["ssq_"+a],l="avg_"+a,g=h[l];g||(h[l]=g=n.map(function(i,k){return i/b[k]}));return m.map(function(i,k){return(i-g[k]/b[k])/(b[k]-d)})};j.value=a;return j};dv.stdev=function(a,f){a=dv.variance(a,f);var j=a.done;a.done=function(d){d=j(d);for(var h=0;h<d.length;++h)d[h]=Math.sqrt(d[h]);return d};return a};
dv.bin=function(a,f,j,d){var h={};h.array=function(b){var n=b.length,m,l,g=j,i=d,k=false,o=false;if(g===undefined){g=Infinity;k=true}if(i===undefined){i=-Infinity;o=true}if(k||o){for(l=0;l<n;++l){m=b[l];if(k&&m<g)g=m;if(o&&m>i)i=m}if(k)g=Math.floor(g/f)*f;if(o)i=Math.ceil(i/f)*f}k=[];o=k.lut=[];var p=i-g,r=Math.ceil(p/f);for(l=0;l<n;++l){m=b[l];m>=i?k.push(r-1):k.push(Math.floor(r*(b[l]-g)/p))}for(l=0;l<r;++l)o.push(g+l*f);return k};h.value=a;return h};
dv.quantile=function(a,f){function j(h,b){for(var n=0,m=h.length-1;n<=m;){var l=n+m>>1,g=h[l];if(g<b)n=l+1;else if(g>b)m=l-1;else return l}h=-n-1;return h<0?-h-1:h}var d={};d.array=function(h){var b,n=h.sorted;if(!n){b=h.type&&h.type==="numeric"?function(i,k){return i-k}:function(i,k){return i<k?-1:i>k?1:0};h.sorted=n=h.slice().sort(b)}var m=[n[0]],l=[],g=l.lut=[];for(b=1;b<=f;++b){m[b]=n[~~(b*(n.length-1)/f)];g.push(b-1)}for(b=0;b<h.length;++b)l.push(Math.max(0,j(m,h[b])-1));return l};d.value=a;
return d};dv.compare={eq:"eq",lt:"lt",le:"le",gt:"gt",ge:"ge",ne:"ne"};dv.eq=function(a,f){if(typeof f!="object")f={val:f};return dv.compare(a,dv.compare.eq,f)};
dv.compare=function(a,f,j){var d={},h;d.table=function(n){h=n[a];return this};var b=j.val;switch(f){case dv.compare.eq:d.test=function(n){return h[n]==b};break;case dv.compare.ne:d.test=function(n){return h[n]!=b};break;case dv.compare.lt:d.test=function(n){return h[n]<b};break;case dv.compare.le:d.test=function(n){return h[n]<=b};break;case dv.compare.gt:d.test=function(n){return h[n]>b};break;case dv.compare.ge:d.test=function(n){return h[n]>=b};break}return d};
dv.graph=function(a,f,j){var d=[],h;d.nodes=a;d.edges=f.length;d.source=f;d.target=j;d.init=function(){var b,n,m,l=[];for(b=0;b<a;++b)l.push([]);for(b=0;b<f.length;++b){n=f[b];m=j[b];l[n].push(m);l[m].push(n)}h=l};d.neighbors=function(b){return h[b]};d.init();return d};dv.graph.indegree=function(a){var f=a.edges,j=a.target,d=dv.array(a.nodes);for(a=0;a<f;++a)d[j[a]]+=1;return d};dv.graph.outdegree=function(a){var f=a.edges,j=a.source,d=dv.array(a.nodes);for(a=0;a<f;++a)d[j[a]]+=1;return d};
dv.graph.degree=function(a){var f=a.edges,j=a.source,d=a.target,h=dv.array(a.nodes);for(a=0;a<f;++a){h[j[a]]+=1;h[d[a]]+=1}return h};
dv.graph.bc=function(a){function f(){var p={};p.centrality=0;p.reset=function(){p.predecessors=[];p.dependency=0;p.distance=-1;p.paths=0;return p};return p.reset()}var j=a.nodes,d,h,b,n,m,l,g,i,k,o;m=0;for(g=[];m<j;++m)g.push(f());for(m=0;m<j;++m){for(n=0;n<j;++n)g[n].reset();i=g[m];i.paths=1;i.distance=0;h=[];for(b=[m];b.length>0;){d=b.shift();h.push(d);k=g[d];d=a.neighbors(d);for(n=0;n<d.length;++n){l=d[n];o=g[l];if(o.distance<0){b.push(l);o.distance=k.distance+1}if(o.distance==k.distance+1){o.paths+=
k.paths;o.predecessors.push(k)}}}for(;h.length>0;){o=h.pop();for(n=0;n<o.predecessors.length;++n){k=o.predecessors[n];k.dependency+=k.paths/o.paths*(1+o.dependency)}if(o!==i)o.centrality+=o.dependency}}return g.map(function(p){return p.centrality})};dv.cluster={};dv.cluster.merge=function(a,f,j,d){a={i:+a,j:+f,prev:j,next:d};if(j)j.next=a;if(d)d.prev=a;return a};
dv.cluster.community=function(a){function f(t,C,H){if(t==C)return 0;else{m+=H;return H}}function j(t,C,H){H*=m;g[t]+=H;e=d(t,C,e);return H}var d=dv.cluster.merge,h,b=0,n=0,m=0,l=a.rows,g=dv.array(l),i,k,o,p,r,s,x,F,q;scores=[];merge=merges=d(-1,-1);e=E=d(-1,-1);maxEdge=d(0,0);b=a.clone();b.visitNonZero(f);m=1/m;b.visitNonZero(j);a=b.values();for(p=0;p<l-1&&E.next;++p){b=-Infinity;maxEdge.i=0;maxEdge.j=0;for(e=E.next;e;e=e.next){i=e.i;k=e.j;if(i!=k){s=i*l+k;x=k*l+i;h=a[s]+a[x]-2*g[i]*g[k];if(h>b){b=
h;maxEdge.i=i;maxEdge.j=k}}}i=maxEdge.i;k=maxEdge.j;if(k<i){h=k;k=i;i=h}s=i*l;x=k*l;for(o=r=0;r<l;++r){F=s+r;q=x+r;h=a[F]+a[q];if(h!=0){o+=h;a[F]=h;a[q]=0}}for(r=0;r<l;++r){s=r*l+i;x=r*l+k;h=a[s]+a[x];if(h!=0){a[s]=h;a[x]=0}}g[i]=o;g[k]=0;for(e=E.next;e;e=e.next)if(e.i==i&&e.j==k||e.i==k&&e.j==i){if(e.prev.next=e.next)e.next.prev=e.prev}else if(e.i==k)e.i=i;else if(e.j==k)e.j=i;n+=b;scores.push(n);merge=d(i,k,merge)}return{merges:merges,scores:scores}};
dv.cluster.groups=function(a,f){var j=a.merges,d=a.scores;a={};var h=1,b,n,m,l,g,i;if(f===undefined||f<0){n=0;f=-1;for(b=-Infinity;n<d.length;++n)if(d[n]>b)b=d[f=n]}n=0;for(m=j.next;n<=f;++n,m=m.next){l=m.i;g=m.j;if((d=a[l])===undefined){d=[l];a[l]=d}if((i=a[g])===undefined)d.push(g);else{for(b=0;b<i.length;++b)d.push(i[b]);delete a[g]}}f=dv.array(j.length+1);for(l in a){d=a[l];for(n=0;n<d.length;++n)f[d[n]]=h;++h}return f};dv.matrix={};
dv.matrix.dense=function(a,f,j){var d={},h=[],b=f,n=a;d.values=function(){return h};d.init=function(m,l,g){d.rows=n=m;d.cols=b=l;h=[];if(g)for(var i=0;i<m*l;++i)h.push(g[i]);else for(i=0;i<m*l;++i)h.push(0)};d.clone=function(){return dv.matrix.dense(n,b,h)};d.like=function(){return dv.matrix.dense(n,b)};d.get=function(m,l){return h[m*b+l]};d.set=function(m,l,g){h[m*b+l]=g};d.scale=function(m){for(var l=0;l<h.length;++l)h[idx]*=m};d.multiply=function(m){if(b!==m.rows){dv.error("Incompatible matrix dimensions");
return null}var l=n,g=m.cols,i,k,o,p,r;r=d.like(l,g);for(i=0;i<l;++i)for(p=k=0;k<g;++k){for(o=0;o<b;++o)p+=d.get(i,o)*m.get(o,k);p&&r.set(i,k,p)}return r};d.visitNonZero=function(m){var l,g,i,k;for(i=0;i<n;++i){l=i*b;for(k=0;k<b;++k){g=l+k;if(u=h[g]){v=m(i,k,u);h[g]=v}}}};d.visit=function(m){var l,g,i,k;for(i=0;i<n;++i){l=i*b;for(k=0;k<b;++k){g=l+k;u=h[g];v=m(i,k,u);h[g]=v}}};d.init(a,f,j);return d};
dv.matrix.sparse=function(a,f,j){var d={},h={},b=f,n=a;d.values=function(){return h};d.init=function(m,l,g){d.rows=n=m;d.cols=b=l;h=[];if(g)for(idx in g)h[idx]=g[idx]};d.clone=function(){return dv.matrix.sparse(n,b,h)};d.like=function(m,l){return dv.matrix.sparse(m,l)};d.get=function(m,l){m=h[m*b+l];return m===undefined?0:m};d.set=function(m,l,g){m=m*b+l;if(g==0)delete h[m];else h[m]=g};d.scale=function(m){for(var l in h)h[l]*=m};d.multiply=function(m){if(b!==m.rows){dv.error("Incompatible matrix dimensions");
return null}var l=n,g=m.cols,i,k,o,p,r;r=d.like(l,g);for(i=0;i<l;++i)for(p=k=0;k<g;++k){for(o=0;o<b;++o)p+=d.get(i,o)*m.get(o,k);p&&r.set(i,k,p)}return r};d.visitNonZero=function(m){var l,g,i,k,o;for(o in h){i=+o;g=i%b;l=(i-g)/b;k=h[i];l=m(l,g,k);if(l==0)delete h[i];else h[i]=l}};d.visit=function(m){var l,g,i,k,o;for(k=0;k<n;++k){l=k*b;for(o=0;o<b;++o){g=l+o;i=(i=h[g])?+i:0;i=m(k,o,i);if(i==0)delete h[g];else h[g]=i}}};d.init(a,f,j);return d};
